// Offline regression against CSV generated by the ORIGINAL ControlPCC.cpp.
// No expected value is calculated from the new kernel.
#include "detail/kernel.hpp"
#include <algorithm>
#include <cmath>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <map>
#include <memory>
#include <set>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

using soft_actuator::detail::Kernel;
using soft_actuator::detail::KernelFeedback;
using soft_actuator::detail::Vec3;

static std::vector<std::string> split(const std::string& line) {
    std::vector<std::string> fields;
    std::istringstream stream(line);
    std::string field;
    while (std::getline(stream, field, ',')) {
        if (!field.empty() && field.back() == '\r') field.pop_back();
        fields.push_back(field);
    }
    return fields;
}

class Row {
    const std::map<std::string, std::size_t>& columns;
    const std::vector<std::string>& values;
public:
    Row(const std::map<std::string, std::size_t>& c, const std::vector<std::string>& v): columns(c),values(v) {}
    const std::string& text(const std::string& name) const { return values.at(columns.at(name)); }
    double number(const std::string& name) const { return std::stod(text(name)); }
    bool flag(const std::string& name) const { return number(name) != 0.; }
    std::uint64_t integer(const std::string& name) const { return std::stoull(text(name)); }
    Vec3 vector(const std::string& prefix, bool xyz=false) const {
        return xyz ? Vec3(number(prefix+"x"),number(prefix+"y"),number(prefix+"z"))
            : Vec3(number(prefix+"0"),number(prefix+"1"),number(prefix+"2"));
    }
    void check(const std::string& name, double actual, bool exact=false) const {
        const double expected = number(name);
        bool equal;
        if (std::isnan(expected)) equal = std::isnan(actual);
        else if (!std::isfinite(expected)) equal = actual == expected;
        else if (!std::isfinite(actual)) equal = false;
        else {
            const double tolerance = exact ? 0. : 1e-8 + 1e-7*std::max(std::abs(expected),std::abs(actual));
            equal = std::abs(actual-expected) <= tolerance;
        }
        if (!equal) {
            std::ostringstream message;
            message << std::setprecision(17) << text("scenario") << " step " << text("step")
                << " " << name << ": expected " << expected << ", got " << actual;
            throw std::runtime_error(message.str());
        }
    }
    void checkVector(const std::string& prefix, const Vec3& actual, bool xyz=false) const {
        if (xyz) { check(prefix+"x",actual.x()); check(prefix+"y",actual.y()); check(prefix+"z",actual.z()); }
        else for (int i=0;i<3;++i) check(prefix+std::to_string(i),actual(i));
    }
};

int main(int argc, char** argv) {
    if (argc != 3) { std::cerr << "Usage: legacy_replay FIXTURE.csv PROFILE.txt\n"; return 2; }
    try {
        const auto model = soft_actuator::loadModel(argv[2]);
        std::ifstream input(argv[1]);
        if (!input) throw std::runtime_error("Cannot open original-output fixture");
        std::string line;
        if (!std::getline(input,line)) throw std::runtime_error("Empty fixture");
        const auto header = split(line);
        std::map<std::string,std::size_t> columns;
        for (std::size_t i=0;i<header.size();++i)
            if (!columns.emplace(header[i],i).second) throw std::runtime_error("Duplicate CSV column");
        std::unique_ptr<Kernel> kernel;
        std::set<std::string> scenarios;
        std::set<int> contactStates;
        bool sawLimited=false, sawInvalid=false, sawRepeated=false;
        std::uint64_t previousSeq=0;
        std::size_t rows=0;
        while (std::getline(input,line)) {
            if (line.empty()) continue;
            const auto fields=split(line);
            if (fields.size()!=header.size()) throw std::runtime_error("CSV column count mismatch");
            const Row row(columns,fields);
            auto pressure=row.vector("pressure_in_");
            if (row.flag("reset")) {
                kernel=std::make_unique<Kernel>(model);
                kernel->reset(row.vector("reset_pressure_"));
                previousSeq=0;
                scenarios.insert(row.text("scenario"));
            }
            if (!kernel) throw std::runtime_error("First fixture row must reset kernel");
            KernelFeedback feedback;
            feedback.position=row.vector("sensor_",true);
            // These axes were generated using ORIGINAL frameTrans.cpp from
            // PNODATA floats, not reconstructed with the new math code.
            feedback.tip_axis=row.vector("tip_axis_",true);
            feedback.frameSeq=row.integer("frame_seq");
            feedback.receiveTimeSec=row.number("receive_sec");
            feedback.appliedPressureKPa=row.vector("applied_");
            feedback.appliedPressureValid=row.flag("applied_valid");
            soft_actuator::pressure_length_model::PressureEnvelope envelope{
                row.number("envelope_min"),row.number("envelope_max")};
            const bool closed=row.text("mode")=="closed";
            if (!closed && row.text("mode")!="open") throw std::runtime_error("Unknown fixture mode");
            const auto result=closed
                ? kernel->closedStep(row.vector("target_",true),feedback,feedback.receiveTimeSec,
                    row.number("abs_limit"),row.flag("envelope_enabled") ? &envelope : nullptr,
                    row.flag("contact_enabled"))
                : kernel->openStep(pressure,row.vector("target_",true));
            row.checkVector("pressure_",result.pressure);
            row.checkVector("model_",result.position,true);
            row.checkVector("unconstrained_",result.unconstrainedPressure);
            row.check("numeric_valid",result.numericValid,true);
            row.check("pressure_limited",result.pressureLimited,true);
            row.checkVector("last_pressure_",kernel->currentPressure());
            row.checkVector("pressure_arg_after_",pressure);
            row.checkVector("free_trim_",kernel->m_positionServoFreeTrimLengthMm);
            row.checkVector("contact_trim_",kernel->m_positionServoContactTrimLengthMm);
            row.checkVector("trim_",kernel->m_positionServoFeedbackTrimLengthMm);
            row.check("contact_state",static_cast<int>(kernel->m_positionServoContactState),true);
            row.checkVector("error_",kernel->m_positionServoActualErrorPccMm,true);
            row.check("error_norm",kernel->m_positionServoActualErrorNormMm);
            row.checkVector("position_residual_",kernel->m_positionServoPositionResidualPccMm,true);
            row.check("position_residual_norm",kernel->m_positionServoPositionResidualNormMm);
            row.checkVector("length_residual_",kernel->m_positionServoLengthResidualMm);
            row.check("length_residual_norm",kernel->m_positionServoLengthResidualNormMm);
            row.checkVector("feedforward_pressure_",kernel->m_positionServoFeedforwardPressureKPa);
            row.checkVector("feedforward_length_",kernel->m_positionServoFeedforwardLengthMm);
            row.check("last_feedback_seq",static_cast<double>(kernel->m_positionServoLastFeedbackFrameSeq),true);
            row.check("feedback_dt",kernel->m_positionServoFeedbackDtSec);
            row.check("load_likely",kernel->m_positionServoLoadLikely,true);
            row.check("freeze_active",kernel->m_positionServoFreezeActive,true);
            contactStates.insert(static_cast<int>(kernel->m_positionServoContactState));
            sawLimited = sawLimited || result.pressureLimited;
            sawInvalid = sawInvalid || !result.numericValid;
            sawRepeated = sawRepeated || (closed && feedback.frameSeq==previousSeq);
            previousSeq=feedback.frameSeq;
            ++rows;
        }
        if (rows<500 || scenarios.size()<14 || contactStates.size()!=5 || !sawLimited || !sawInvalid || !sawRepeated)
            throw std::runtime_error("Fixture lost required trajectory/state coverage");
        std::cout << "Replayed " << rows << " original-output rows in " << scenarios.size()
            << " scenarios; all pressure, model, trim, residual and contact states match.\n";
    } catch (const std::exception& error) {
        std::cerr << error.what() << '\n';
        return 1;
    }
}
